# Splunk Universal Forwarder inputs.conf
# Location on Windows victim:
# C:\Program Files\SplunkUniversalForwarder\etc\system\local\inputs.conf

[WinEventLog://Security]
disabled = 0
index = endpoint
renderXml = true

[WinEventLog://System]
disabled = 0
index = endpoint
renderXml = true

[WinEventLog://Application]
disabled = 0
index = endpoint
renderXml = true

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
disabled = 0
index = endpoint
renderXml = true
